version: "3.8"

services:
  server:
    image: nginx:alpine
    platform: linux/arm64
    restart: unless-stopped
    ports:
      - 81:80
      - 444:443
    networks:
      - app-network
    volumes:
      - .:/var/www:delegated  # Agregado :delegated para mejor rendimiento
      - ./nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: mysql:8.0
    platform: linux/arm64
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network
    volumes:
      - dbdata:/var/lib/mysql

  app:
    build: 
      context: .
      dockerfile: docker/Dockerfile
      platforms:
        - linux/arm64
    restart: unless-stopped
    working_dir: /var/www  # Agregado working_dir
    networks:
      - app-network
    volumes:
      - .:/var/www:delegated  # Agregado :delegated para mejor rendimiento

  node:
    image: node:16-alpine
    platform: linux/arm64
    working_dir: /var/www
    volumes:
      - .:/var/www:delegated
      - /var/www/node_modules
    command: sh /var/www/node_start.sh
    depends_on:
      - app

networks:
  app-network:
    driver: bridge

volumes:
  dbdata: